# Generated by Django 3.2.6 on 2021-08-26 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210823_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
