# Generated by Django 3.2.6 on 2021-08-31 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_answer_submission_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswerSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_points', models.FloatField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exercise')),
                ('latest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='useranswersummary',
            constraint=models.UniqueConstraint(fields=('user', 'exercise'), name='unique_user_exercise_summary'),
        ),
    ]
