# Generated by Django 3.2.6 on 2021-09-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_count_useranswersummary_answer_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='group',
            field=models.CharField(default='handout', max_length=1024),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='topic',
            field=models.CharField(default='while', max_length=1024),
            preserve_default=False,
        ),
    ]
