# Generated by Django 3.2.6 on 2021-09-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210903_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('CODE', 'Code'), ('QUIZ', 'Quiz'), ('TEXT', 'Text'), ('CSS', 'CSS')], max_length=4),
        ),
    ]
