# Generated by Django 3.2.6 on 2021-10-04 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_exercise_type'),
        ('core', '0007_user_password_email_sent'),
        ('core', '0008_auto_20210930_1151'),
    ]

    operations = [
    ]
