# Generated by Django 3.2.6 on 2021-10-06 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_summary_answer_test_results'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='long_answer',
            new_name='student_input',
        ),
    ]
