# Generated by Django 3.2.6 on 2022-01-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_exercise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
