# Generated by Django 3.2.6 on 2022-08-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_exercise_allow_submissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='repo_last_git_output',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='offering',
            name='repo_status',
            field=models.IntegerField(choices=[(0, 'EMPTY'), (1, 'CLONING'), (2, 'READY'), (3, 'UPDATING'), (4, 'ERROR')], default=0),
        ),
        migrations.AddField(
            model_name='offering',
            name='repo_token',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Token'),
        ),
        migrations.AddField(
            model_name='offering',
            name='repo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='offering',
            name='repo_user',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Usuário'),
        ),
    ]
