version: '3.8'

services:
  web:
    build: ..
    command: gunicorn devlife_support.wsgi:application  --bind 0.0.0.0:8000
    expose: 
      - 8000
    env_file:
      - ./.env.prod
    volumes:
      - static_volume:/app/.static
  
  nginx:
    build: nginx
    ports:
      - 1337:80
    depends_on: 
      - web
    volumes:
      - static_volume:/app/.static

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ./.env.prod

  
volumes:
  static_volume:
  postgres_data: